name: Upload to S3

on:
   push:
      branches:
         - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: hkusu/s3-upload-action@v2
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: 'us-east-1'
       aws-bucket: ${{ secrets.AWS_BUCKET }}
       file-path: 'C:\Users\Karan\Documents\Git Actions\rough work\buddha.jpg'